$(document).ready(function(){
	var abrir1 = $(".pabrir1");
	var link1 = $(".link1");
	var abrir2 = $(".pabrir2");
	var link2 = $(".link2");
	var abrir3 = $(".pabrir3");
	var link3 = $(".link3");
	var abrir4 = $(".pabrir4");
	var link4 = $(".link4");
	var abrir5 = $(".pabrir5");
	var link5 = $(".link5");
	var abrir6 = $(".pabrir6");
	var link6 = $(".link6");
	var abrir7 = $(".pabrir7");
	var link7 = $(".link7");
    var abriredu = $(".pabriredu");
    var linkedu = $(".linkedu");
    var abrirraul = $(".pabrirraul");
    var linkraul = $(".linkraul");
    var abrirandre = $(".pabrirandre");
    var linkandre = $(".linkandre");
    var abrircascola = $(".pabrircascola");
    var linkcascola = $(".linkcascola");
    var abrirpai = $(".pabrirpai");
    var linkpai = $(".linkpai");
    var abrirdani = $(".pabrirdani");
    var linkdani = $(".linkdani");
    var abrirjefferson = $(".pabrirjefferson");
    var linkjefferson = $(".linkjefferson");
    var abrirbatatinha = $(".pabrirbatatinha");
    var linkbatatinha = $(".linkbatatinha");

	abrir1.click(function(){
		link2.fadeOut(0);
		link3.fadeOut(0);
		link4.fadeOut(0);
		link5.fadeOut(0);
		link6.fadeOut(0);
		link7.fadeOut(0);
        linkedu.fadeOut(0);
        linkraul.fadeOut(0);
        linkandre.fadeOut(0);
        linkcascola.fadeOut(0);
        linkpai.fadeOut(0);
        linkdani.fadeOut(0);
        linkjefferson.fadeOut(0);
        linkbatatinha.fadeOut(0);
		link1.fadeIn(0);
		return false;
	});
	abrir2.click(function(){
		link1.fadeOut(0);
		link3.fadeOut(0);
		link4.fadeOut(0);
		link5.fadeOut(0);
		link6.fadeOut(0);
		link7.fadeOut(0);
        linkedu.fadeOut(0);
        linkraul.fadeOut(0);
        linkandre.fadeOut(0);
        linkcascola.fadeOut(0);
        linkpai.fadeOut(0);
        linkdani.fadeOut(0);
        linkjefferson.fadeOut(0);
        linkbatatinha.fadeOut(0);
        link2.fadeIn(0);
		return false;
	});
	abrir3.click(function(){
		link1.fadeOut(0);
		link2.fadeOut(0);
		link4.fadeOut(0);
		link5.fadeOut(0);
		link6.fadeOut(0);
		link7.fadeOut(0);
        linkedu.fadeOut(0);
        linkraul.fadeOut(0);
        linkandre.fadeOut(0);
        linkcascola.fadeOut(0);
        linkpai.fadeOut(0);
        linkdani.fadeOut(0);
        linkjefferson.fadeOut(0);
        linkbatatinha.fadeOut(0);
        link3.fadeIn(0);
		return false;
	});
	abrir4.click(function(){
		link1.fadeOut(0);
		link2.fadeOut(0);
		link3.fadeOut(0);
		link5.fadeOut(0);
		link6.fadeOut(0);
		link7.fadeOut(0);
        linkedu.fadeOut(0);
        linkraul.fadeOut(0);
        linkandre.fadeOut(0);
        linkcascola.fadeOut(0);
        linkpai.fadeOut(0);
        linkdani.fadeOut(0);
        linkjefferson.fadeOut(0);
        linkbatatinha.fadeOut(0);
        link4.fadeIn(0);
		return false;
	});
	abrir5.click(function(){
		link1.fadeOut(0);
		link2.fadeOut(0);
		link3.fadeOut(0);
		link4.fadeOut(0);
		link6.fadeOut(0);
		link7.fadeOut(0);
        linkedu.fadeOut(0);
        linkraul.fadeOut(0);
        linkandre.fadeOut(0);
        linkcascola.fadeOut(0);
        linkpai.fadeOut(0);
        linkdani.fadeOut(0);
        linkjefferson.fadeOut(0);
        linkbatatinha.fadeOut(0);
        link5.fadeIn(0);
		return false;
	});
	abrir6.click(function(){
		link1.fadeOut(0);
		link2.fadeOut(0);
		link3.fadeOut(0);
		link4.fadeOut(0);
		link5.fadeOut(0);
		link7.fadeOut(0);
        linkedu.fadeOut(0);
        linkraul.fadeOut(0);
        linkandre.fadeOut(0);
        linkcascola.fadeOut(0);
        linkpai.fadeOut(0);
        linkdani.fadeOut(0);
        linkjefferson.fadeOut(0);
        linkbatatinha.fadeOut(0);
        link6.fadeIn(0);
		return false;
	});
	abrir7.click(function(){
		link1.fadeOut(0);
		link2.fadeOut(0);
		link3.fadeOut(0);
		link4.fadeOut(0);
		link5.fadeOut(0);
		link6.fadeOut(0);
        linkedu.fadeOut(0);
        linkraul.fadeOut(0);
        linkandre.fadeOut(0);
        linkcascola.fadeOut(0);
        linkpai.fadeOut(0);
        linkdani.fadeOut(0);
        linkjefferson.fadeOut(0);
        linkbatatinha.fadeOut(0);
        link7.fadeIn(0);
		return false;
	});
	abriredu.click(function(){
		link2.fadeOut(0);
		linkedu.fadeIn(0);
		return false;
	});
	abrirraul.click(function(){
		link2.fadeOut(0);
		linkraul.fadeIn(0);
		return false;
	});
	abrirandre.click(function(){
		link2.fadeOut(0);
		linkandre.fadeIn(0);
		return false;
	});
	abrircascola.click(function(){
		link2.fadeOut(0);
		linkcascola.fadeIn(0);
		return false;
	});
	abrirpai.click(function(){
		link2.fadeOut(0);
		linkpai.fadeIn(0);
		return false;
	});
	abrirdani.click(function(){
		link2.fadeOut(0);
		linkdani.fadeIn(0);
		return false;
	});
	abrirjefferson.click(function(){
		link2.fadeOut(0);
		linkjefferson.fadeIn(0);
		return false;
	});
	abrirbatatinha.click(function(){
		link2.fadeOut(0);
		linkbatatinha.fadeIn(0);
		return false;
	});
});